# Generated by Django 4.2.7 on 2026-04-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_script_unique_script_name_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='ai_generated',
            field=models.BooleanField(default=False, verbose_name='AI生成'),
        ),
        migrations.AddField(
            model_name='script',
            name='heal_enabled',
            field=models.BooleanField(default=False, verbose_name='启用自愈'),
        ),
        migrations.AlterField(
            model_name='script',
            name='framework',
            field=models.CharField(choices=[('playwright', 'Playwright'), ('appium', 'Appium'), ('httprunner', 'HttpRunner')], default='playwright', max_length=20, verbose_name='测试框架'),
        ),
    ]
