# Generated by Django 4.2.7 on 2026-04-25 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scripts', '0007_v2_add_ai_fields_and_heallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '生成中'), ('reviewing', 'AI评审中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数')),
                ('completed_count', models.IntegerField(default=0, verbose_name='已完成')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('results', models.JSONField(default=list, verbose_name='生成结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '批量生成任务',
                'verbose_name_plural': '批量生成任务',
                'db_table': 'scripts_batchtask',
                'ordering': ['-created_at'],
            },
        ),
    ]
