# Generated by Django 4.2.7 on 2026-04-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0007_v2_add_ai_fields_and_heallog'),
        ('executions', '0006_execution_display_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField(verbose_name='步骤索引')),
                ('step_name', models.CharField(blank=True, max_length=200, verbose_name='步骤名称')),
                ('original_locator', models.CharField(max_length=500, verbose_name='原始定位器')),
                ('suggested_locator', models.CharField(blank=True, max_length=500, verbose_name='推荐替代定位器')),
                ('locator_type', models.CharField(choices=[('css', 'CSS选择器'), ('xpath', 'XPath'), ('data-testid', 'data-testid属性'), ('id', 'ID属性'), ('text', '文本选择器')], default='css', max_length=20, verbose_name='定位器类型')),
                ('heal_status', models.CharField(choices=[('success', '修复成功'), ('failed', '修复失败'), ('pending', '待审核')], default='pending', max_length=20, verbose_name='修复状态')),
                ('heal_strategy', models.CharField(choices=[('llm_recommend', 'LLM推荐'), ('dom_analysis', 'DOM分析'), ('rule_based', '规则匹配')], default='llm_recommend', max_length=20, verbose_name='修复策略')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('reason', models.TextField(blank=True, verbose_name='修复原因说明')),
                ('dom_snapshot', models.TextField(blank=True, verbose_name='DOM快照')),
                ('llm_provider', models.CharField(blank=True, max_length=50, verbose_name='LLM提供商')),
                ('token_consumed', models.IntegerField(default=0, verbose_name='Token消耗量')),
                ('auto_applied', models.BooleanField(default=False, verbose_name='已自动应用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal_logs', to='executions.execution', verbose_name='关联执行记录')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal_logs', to='scripts.script', verbose_name='关联脚本')),
            ],
            options={
                'verbose_name': '自愈日志',
                'verbose_name_plural': '自愈日志',
                'db_table': 'executions_heallog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['script', 'heal_status'], name='idx_heal_script_status'), models.Index(fields=['execution', 'step_index'], name='idx_heal_exec_step')],
            },
        ),
    ]
