# Generated by Django 4.2.7 on 2026-04-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键名')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('category', models.CharField(choices=[('provider', 'Provider 选择'), ('openai', 'OpenAI 配置'), ('qwen', '通义千问配置'), ('general', '通用参数')], default='general', max_length=20, verbose_name='分类')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
                'db_table': 'settings_ai_setting',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('healing', '智能自愈'), ('nl2script', 'NL2Script')], max_length=20, verbose_name='服务类型')),
                ('scenario', models.CharField(choices=[('strict', '严格模式'), ('relaxed', '宽松模式'), ('custom', '自定义')], max_length=20, verbose_name='场景')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('system_prompt', models.TextField(verbose_name='系统提示词')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('temperature', models.FloatField(default=0.3, verbose_name='温度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'db_table': 'settings_prompt_template',
                'ordering': ['service', 'scenario'],
                'unique_together': {('service', 'scenario')},
            },
        ),
    ]
